crawler/bimebazar/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'vehicles/$', views.car_list)
]

crawler/crawler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^forms/', include('form_test.urls')),
    url(r'^bimebazar/', include('bimebazar.urls')),
    url(r'^admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()

crawler/form_test/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'contact/$', views.get_form, name= 'contact'),
    url(r'thanks/$', views.get_form),
]

crawler/bimebazar/models.py
from django.db import models


class AbstractVehicle(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    class Meta:
        abstract = True


class VehicleBrand(AbstractVehicle):
    usage_count = models.PositiveIntegerField(default=0)


class VehicleModel(AbstractVehicle):
    CAR, AUTOCAR, CARRIER, MOTORCYCLE = 'car', 'autocar', 'carrier', 'motorcycle'
    VEHICLE_TYPE_CHOICES = [
        (CAR, 'سواری'),
        (AUTOCAR, 'ون'),
        (CARRIER, 'باری'),
        (MOTORCYCLE, 'موتورسیکلت')
    ]
    
    vehicle_brand = models.ForeignKey(VehicleBrand, on_delete=models.SET_NULL, null=True, related_name='vehicle_models')
    vehicle_type = models.CharField(max_length=20, choices=VEHICLE_TYPE_CHOICES)

    def __str__(self):
        return self.name

crawler/form_test/models.py
from django.db import models

# Create your models here.

crawler/form_test/forms.py
from django import forms

class Contact_Us(forms.Form):
    name = forms.CharField(label='Youre name', max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

crawler/bimebazar/views.py
import requests

from django.shortcuts import render
from django.http import HttpResponse

from .models import VehicleBrand, VehicleModel

def car_list(request):
    response = requests.get('https://bimebazar.com/order/api/car-list/')
    if response.status_code == 200:
        vehicle_list = response.json()
        for vehicle_type, brands in vehicle_list.items():
            for brand in brands:
                try:
                    vehicle_brand, _ = VehicleBrand.objects.get_or_create(slug=brand['name_en'], defaults=dict(
                        name=brand['name'],
                        usage_count=brand['uses'],
                    ))
                    for model in brand['models']:
                        VehicleModel.objects.get_or_create(slug=model['name_en'], defaults=dict(
                            name=model['name'],
                            vehicle_type=vehicle_type,
                            vehicle_brand=vehicle_brand,
                        ))
                except:
                    continue

    return render(request, 'bimebazar/vehicles.html', context={
        'vehicle_brands': VehicleBrand.objects.all()
    })

crawler/form_test/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import Contact_Us


def get_form(request):

    if request.method == 'POST':
        form = Contact_Us(request.POST)
        if form.is_valid():
            your_email = form.cleaned_data['email']
            # return HttpResponse(your_email)
            message = "You're email submited"
            return HttpResponseRedirect(reverse('contact'))

    else:
        form = Contact_Us()
        message = ''

    return render(request, 'form_test/contact.html', {'form': form, 'message': message})

crawler/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

crawler/templates/bimebazar/vehicles.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block title %}لیست وسایل نقلیه{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/bimebazar/vehicles.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1>لیست وسایل نقلیه</h1>
    <div class="panel-group" id="accordion">
        {% for vehicle_brand in vehicle_brands %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}">
                            {{ vehicle_brand.name }} ({{ vehicle_brand.vehicle_models.count }})
                        </a>
                    </h4>
                </div>
                <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
                    {% for vehicle_model in vehicle_brand.vehicle_models.all %}
                        <div class="panel-body">{{ vehicle_model.get_vehicle_type_display }} - {{ vehicle_model.name }}</div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

crawler/templates/form_test/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>form</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
    <p>{{ message }}</p>
</body>
</html>

crawler/templates/form_test/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thanks</title>
</head>
<body>
<h1>Thanks</h1>
</body>
</html>